package com.github.xuzw.activity.api.svg;

import java.util.Random;

/**
 * @author 徐泽威 xuzewei_2012@126.com
 * @time 2017年3月24日 下午1:09:29
 */
public enum MaterialDesignSymbol {
    ic_3d_rotation_24px("ic-3d-rotation-24px"), // ic-3d-rotation-24px
    ic_accessibility_24px("ic-accessibility-24px"), // ic-accessibility-24px
    ic_accessible_24px("ic-accessible-24px"), // ic-accessible-24px
    ic_account_balance_24px("ic-account-balance-24px"), // ic-account-balance-24px
    ic_account_balance_wallet_24px("ic-account-balance-wallet-24px"), // ic-account-balance-wallet-24px
    ic_account_box_24px("ic-account-box-24px"), // ic-account-box-24px
    ic_account_circle_24px("ic-account-circle-24px"), // ic-account-circle-24px
    ic_add_shopping_cart_24px("ic-add-shopping-cart-24px"), // ic-add-shopping-cart-24px
    ic_alarm_24px("ic-alarm-24px"), // ic-alarm-24px
    ic_alarm_add_24px("ic-alarm-add-24px"), // ic-alarm-add-24px
    ic_alarm_off_24px("ic-alarm-off-24px"), // ic-alarm-off-24px
    ic_alarm_on_24px("ic-alarm-on-24px"), // ic-alarm-on-24px
    ic_all_out_24px("ic-all-out-24px"), // ic-all-out-24px
    ic_android_24px("ic-android-24px"), // ic-android-24px
    ic_announcement_24px("ic-announcement-24px"), // ic-announcement-24px
    ic_aspect_ratio_24px("ic-aspect-ratio-24px"), // ic-aspect-ratio-24px
    ic_assessment_24px("ic-assessment-24px"), // ic-assessment-24px
    ic_assignment_24px("ic-assignment-24px"), // ic-assignment-24px
    ic_assignment_ind_24px("ic-assignment-ind-24px"), // ic-assignment-ind-24px
    ic_assignment_late_24px("ic-assignment-late-24px"), // ic-assignment-late-24px
    ic_assignment_return_24px("ic-assignment-return-24px"), // ic-assignment-return-24px
    ic_assignment_returned_24px("ic-assignment-returned-24px"), // ic-assignment-returned-24px
    ic_assignment_turned_in_24px("ic-assignment-turned-in-24px"), // ic-assignment-turned-in-24px
    ic_autorenew_24px("ic-autorenew-24px"), // ic-autorenew-24px
    ic_backup_24px("ic-backup-24px"), // ic-backup-24px
    ic_book_24px("ic-book-24px"), // ic-book-24px
    ic_bookmark_24px("ic-bookmark-24px"), // ic-bookmark-24px
    ic_bookmark_border_24px("ic-bookmark-border-24px"), // ic-bookmark-border-24px
    ic_bug_report_24px("ic-bug-report-24px"), // ic-bug-report-24px
    ic_build_24px("ic-build-24px"), // ic-build-24px
    ic_cached_24px("ic-cached-24px"), // ic-cached-24px
    ic_camera_enhance_24px("ic-camera-enhance-24px"), // ic-camera-enhance-24px
    ic_card_giftcard_24px("ic-card-giftcard-24px"), // ic-card-giftcard-24px
    ic_card_membership_24px("ic-card-membership-24px"), // ic-card-membership-24px
    ic_card_travel_24px("ic-card-travel-24px"), // ic-card-travel-24px
    ic_change_history_24px("ic-change-history-24px"), // ic-change-history-24px
    ic_check_circle_24px("ic-check-circle-24px"), // ic-check-circle-24px
    ic_chrome_reader_mode_24px("ic-chrome-reader-mode-24px"), // ic-chrome-reader-mode-24px
    ic_class_24px("ic-class-24px"), // ic-class-24px
    ic_code_24px("ic-code-24px"), // ic-code-24px
    ic_compare_arrows_24px("ic-compare-arrows-24px"), // ic-compare-arrows-24px
    ic_copyright_24px("ic-copyright-24px"), // ic-copyright-24px
    ic_credit_card_24px("ic-credit-card-24px"), // ic-credit-card-24px
    ic_dashboard_24px("ic-dashboard-24px"), // ic-dashboard-24px
    ic_date_range_24px("ic-date-range-24px"), // ic-date-range-24px
    ic_delete_24px("ic-delete-24px"), // ic-delete-24px
    ic_delete_forever_24px("ic-delete-forever-24px"), // ic-delete-forever-24px
    ic_description_24px("ic-description-24px"), // ic-description-24px
    ic_dns_24px("ic-dns-24px"), // ic-dns-24px
    ic_done_24px("ic-done-24px"), // ic-done-24px
    ic_done_all_24px("ic-done-all-24px"), // ic-done-all-24px
    ic_donut_large_24px("ic-donut-large-24px"), // ic-donut-large-24px
    ic_donut_small_24px("ic-donut-small-24px"), // ic-donut-small-24px
    ic_eject_24px("ic-eject-24px"), // ic-eject-24px
    ic_euro_symbol_24px("ic-euro-symbol-24px"), // ic-euro-symbol-24px
    ic_event_24px("ic-event-24px"), // ic-event-24px
    ic_event_seat_24px("ic-event-seat-24px"), // ic-event-seat-24px
    ic_exit_to_app_24px("ic-exit-to-app-24px"), // ic-exit-to-app-24px
    ic_explore_24px("ic-explore-24px"), // ic-explore-24px
    ic_extension_24px("ic-extension-24px"), // ic-extension-24px
    ic_face_24px("ic-face-24px"), // ic-face-24px
    ic_favorite_24px("ic-favorite-24px"), // ic-favorite-24px
    ic_favorite_border_24px("ic-favorite-border-24px"), // ic-favorite-border-24px
    ic_feedback_24px("ic-feedback-24px"), // ic-feedback-24px
    ic_find_in_page_24px("ic-find-in-page-24px"), // ic-find-in-page-24px
    ic_find_replace_24px("ic-find-replace-24px"), // ic-find-replace-24px
    ic_fingerprint_24px("ic-fingerprint-24px"), // ic-fingerprint-24px
    ic_flight_land_24px("ic-flight-land-24px"), // ic-flight-land-24px
    ic_flight_takeoff_24px("ic-flight-takeoff-24px"), // ic-flight-takeoff-24px
    ic_flip_to_back_24px("ic-flip-to-back-24px"), // ic-flip-to-back-24px
    ic_flip_to_front_24px("ic-flip-to-front-24px"), // ic-flip-to-front-24px
    ic_g_translate_24px("ic-g-translate-24px"), // ic-g-translate-24px
    ic_gavel_24px("ic-gavel-24px"), // ic-gavel-24px
    ic_get_app_24px("ic-get-app-24px"), // ic-get-app-24px
    ic_gif_24px("ic-gif-24px"), // ic-gif-24px
    ic_grade_24px("ic-grade-24px"), // ic-grade-24px
    ic_group_work_24px("ic-group-work-24px"), // ic-group-work-24px
    ic_help_24px("ic-help-24px"), // ic-help-24px
    ic_help_outline_24px("ic-help-outline-24px"), // ic-help-outline-24px
    ic_highlight_off_24px("ic-highlight-off-24px"), // ic-highlight-off-24px
    ic_history_24px("ic-history-24px"), // ic-history-24px
    ic_home_24px("ic-home-24px"), // ic-home-24px
    ic_hourglass_empty_24px("ic-hourglass-empty-24px"), // ic-hourglass-empty-24px
    ic_hourglass_full_24px("ic-hourglass-full-24px"), // ic-hourglass-full-24px
    ic_http_24px("ic-http-24px"), // ic-http-24px
    ic_https_24px("ic-https-24px"), // ic-https-24px
    ic_important_devices_24px("ic-important-devices-24px"), // ic-important-devices-24px
    ic_info_24px("ic-info-24px"), // ic-info-24px
    ic_info_outline_24px("ic-info-outline-24px"), // ic-info-outline-24px
    ic_input_24px("ic-input-24px"), // ic-input-24px
    ic_invert_colors_24px("ic-invert-colors-24px"), // ic-invert-colors-24px
    ic_label_24px("ic-label-24px"), // ic-label-24px
    ic_label_outline_24px("ic-label-outline-24px"), // ic-label-outline-24px
    ic_language_24px("ic-language-24px"), // ic-language-24px
    ic_launch_24px("ic-launch-24px"), // ic-launch-24px
    ic_lightbulb_outline_24px("ic-lightbulb-outline-24px"), // ic-lightbulb-outline-24px
    ic_line_style_24px("ic-line-style-24px"), // ic-line-style-24px
    ic_line_weight_24px("ic-line-weight-24px"), // ic-line-weight-24px
    ic_list_24px("ic-list-24px"), // ic-list-24px
    ic_lock_24px("ic-lock-24px"), // ic-lock-24px
    ic_lock_open_24px("ic-lock-open-24px"), // ic-lock-open-24px
    ic_lock_outline_24px("ic-lock-outline-24px"), // ic-lock-outline-24px
    ic_loyalty_24px("ic-loyalty-24px"), // ic-loyalty-24px
    ic_markunread_mailbox_24px("ic-markunread-mailbox-24px"), // ic-markunread-mailbox-24px
    ic_motorcycle_24px("ic-motorcycle-24px"), // ic-motorcycle-24px
    ic_note_add_24px("ic-note-add-24px"), // ic-note-add-24px
    ic_offline_pin_24px("ic-offline-pin-24px"), // ic-offline-pin-24px
    ic_opacity_24px("ic-opacity-24px"), // ic-opacity-24px
    ic_open_in_browser_24px("ic-open-in-browser-24px"), // ic-open-in-browser-24px
    ic_open_in_new_24px("ic-open-in-new-24px"), // ic-open-in-new-24px
    ic_open_with_24px("ic-open-with-24px"), // ic-open-with-24px
    ic_pageview_24px("ic-pageview-24px"), // ic-pageview-24px
    ic_pan_tool_24px("ic-pan-tool-24px"), // ic-pan-tool-24px
    ic_payment_24px("ic-payment-24px"), // ic-payment-24px
    ic_perm_camera_mic_24px("ic-perm-camera-mic-24px"), // ic-perm-camera-mic-24px
    ic_perm_contact_calendar_24px("ic-perm-contact-calendar-24px"), // ic-perm-contact-calendar-24px
    ic_perm_data_setting_24px("ic-perm-data-setting-24px"), // ic-perm-data-setting-24px
    ic_perm_device_information_24px("ic-perm-device-information-24px"), // ic-perm-device-information-24px
    ic_perm_identity_24px("ic-perm-identity-24px"), // ic-perm-identity-24px
    ic_perm_media_24px("ic-perm-media-24px"), // ic-perm-media-24px
    ic_perm_phone_msg_24px("ic-perm-phone-msg-24px"), // ic-perm-phone-msg-24px
    ic_perm_scan_wifi_24px("ic-perm-scan-wifi-24px"), // ic-perm-scan-wifi-24px
    ic_pets_24px("ic-pets-24px"), // ic-pets-24px
    ic_picture_in_picture_24px("ic-picture-in-picture-24px"), // ic-picture-in-picture-24px
    ic_picture_in_picture_alt_24px("ic-picture-in-picture-alt-24px"), // ic-picture-in-picture-alt-24px
    ic_play_for_work_24px("ic-play-for-work-24px"), // ic-play-for-work-24px
    ic_polymer_24px("ic-polymer-24px"), // ic-polymer-24px
    ic_power_settings_new_24px("ic-power-settings-new-24px"), // ic-power-settings-new-24px
    ic_pregnant_woman_24px("ic-pregnant-woman-24px"), // ic-pregnant-woman-24px
    ic_print_24px("ic-print-24px"), // ic-print-24px
    ic_query_builder_24px("ic-query-builder-24px"), // ic-query-builder-24px
    ic_question_answer_24px("ic-question-answer-24px"), // ic-question-answer-24px
    ic_receipt_24px("ic-receipt-24px"), // ic-receipt-24px
    ic_record_voice_over_24px("ic-record-voice-over-24px"), // ic-record-voice-over-24px
    ic_redeem_24px("ic-redeem-24px"), // ic-redeem-24px
    ic_remove_shopping_cart_24px("ic-remove-shopping-cart-24px"), // ic-remove-shopping-cart-24px
    ic_reorder_24px("ic-reorder-24px"), // ic-reorder-24px
    ic_report_problem_24px("ic-report-problem-24px"), // ic-report-problem-24px
    ic_restore_24px("ic-restore-24px"), // ic-restore-24px
    ic_restore_page_24px("ic-restore-page-24px"), // ic-restore-page-24px
    ic_room_24px("ic-room-24px"), // ic-room-24px
    ic_rounded_corner_24px("ic-rounded-corner-24px"), // ic-rounded-corner-24px
    ic_rowing_24px("ic-rowing-24px"), // ic-rowing-24px
    ic_schedule_24px("ic-schedule-24px"), // ic-schedule-24px
    ic_search_24px("ic-search-24px"), // ic-search-24px
    ic_settings_24px("ic-settings-24px"), // ic-settings-24px
    ic_settings_applications_24px("ic-settings-applications-24px"), // ic-settings-applications-24px
    ic_settings_backup_restore_24px("ic-settings-backup-restore-24px"), // ic-settings-backup-restore-24px
    ic_settings_bluetooth_24px("ic-settings-bluetooth-24px"), // ic-settings-bluetooth-24px
    ic_settings_brightness_24px("ic-settings-brightness-24px"), // ic-settings-brightness-24px
    ic_settings_cell_24px("ic-settings-cell-24px"), // ic-settings-cell-24px
    ic_settings_ethernet_24px("ic-settings-ethernet-24px"), // ic-settings-ethernet-24px
    ic_settings_input_antenna_24px("ic-settings-input-antenna-24px"), // ic-settings-input-antenna-24px
    ic_settings_input_component_24px("ic-settings-input-component-24px"), // ic-settings-input-component-24px
    ic_settings_input_composite_24px("ic-settings-input-composite-24px"), // ic-settings-input-composite-24px
    ic_settings_input_hdmi_24px("ic-settings-input-hdmi-24px"), // ic-settings-input-hdmi-24px
    ic_settings_input_svideo_24px("ic-settings-input-svideo-24px"), // ic-settings-input-svideo-24px
    ic_settings_overscan_24px("ic-settings-overscan-24px"), // ic-settings-overscan-24px
    ic_settings_phone_24px("ic-settings-phone-24px"), // ic-settings-phone-24px
    ic_settings_power_24px("ic-settings-power-24px"), // ic-settings-power-24px
    ic_settings_remote_24px("ic-settings-remote-24px"), // ic-settings-remote-24px
    ic_settings_voice_24px("ic-settings-voice-24px"), // ic-settings-voice-24px
    ic_shop_24px("ic-shop-24px"), // ic-shop-24px
    ic_shop_two_24px("ic-shop-two-24px"), // ic-shop-two-24px
    ic_shopping_basket_24px("ic-shopping-basket-24px"), // ic-shopping-basket-24px
    ic_shopping_cart_24px("ic-shopping-cart-24px"), // ic-shopping-cart-24px
    ic_speaker_notes_24px("ic-speaker-notes-24px"), // ic-speaker-notes-24px
    ic_speaker_notes_off_24px("ic-speaker-notes-off-24px"), // ic-speaker-notes-off-24px
    ic_spellcheck_24px("ic-spellcheck-24px"), // ic-spellcheck-24px
    ic_stars_24px("ic-stars-24px"), // ic-stars-24px
    ic_store_24px("ic-store-24px"), // ic-store-24px
    ic_subject_24px("ic-subject-24px"), // ic-subject-24px
    ic_supervisor_account_24px("ic-supervisor-account-24px"), // ic-supervisor-account-24px
    ic_swap_horiz_24px("ic-swap-horiz-24px"), // ic-swap-horiz-24px
    ic_swap_vert_24px("ic-swap-vert-24px"), // ic-swap-vert-24px
    ic_swap_vertical_circle_24px("ic-swap-vertical-circle-24px"), // ic-swap-vertical-circle-24px
    ic_system_update_alt_24px("ic-system-update-alt-24px"), // ic-system-update-alt-24px
    ic_tab_24px("ic-tab-24px"), // ic-tab-24px
    ic_tab_unselected_24px("ic-tab-unselected-24px"), // ic-tab-unselected-24px
    ic_theaters_24px("ic-theaters-24px"), // ic-theaters-24px
    ic_thumb_down_24px("ic-thumb-down-24px"), // ic-thumb-down-24px
    ic_thumb_up_24px("ic-thumb-up-24px"), // ic-thumb-up-24px
    ic_thumbs_up_down_24px("ic-thumbs-up-down-24px"), // ic-thumbs-up-down-24px
    ic_timeline_24px("ic-timeline-24px"), // ic-timeline-24px
    ic_toc_24px("ic-toc-24px"), // ic-toc-24px
    ic_today_24px("ic-today-24px"), // ic-today-24px
    ic_toll_24px("ic-toll-24px"), // ic-toll-24px
    ic_touch_app_24px("ic-touch-app-24px"), // ic-touch-app-24px
    ic_track_changes_24px("ic-track-changes-24px"), // ic-track-changes-24px
    ic_translate_24px("ic-translate-24px"), // ic-translate-24px
    ic_trending_down_24px("ic-trending-down-24px"), // ic-trending-down-24px
    ic_trending_flat_24px("ic-trending-flat-24px"), // ic-trending-flat-24px
    ic_trending_up_24px("ic-trending-up-24px"), // ic-trending-up-24px
    ic_turned_in_24px("ic-turned-in-24px"), // ic-turned-in-24px
    ic_turned_in_not_24px("ic-turned-in-not-24px"), // ic-turned-in-not-24px
    ic_update_24px("ic-update-24px"), // ic-update-24px
    ic_verified_user_24px("ic-verified-user-24px"), // ic-verified-user-24px
    ic_view_agenda_24px("ic-view-agenda-24px"), // ic-view-agenda-24px
    ic_view_array_24px("ic-view-array-24px"), // ic-view-array-24px
    ic_view_carousel_24px("ic-view-carousel-24px"), // ic-view-carousel-24px
    ic_view_column_24px("ic-view-column-24px"), // ic-view-column-24px
    ic_view_day_24px("ic-view-day-24px"), // ic-view-day-24px
    ic_view_headline_24px("ic-view-headline-24px"), // ic-view-headline-24px
    ic_view_list_24px("ic-view-list-24px"), // ic-view-list-24px
    ic_view_module_24px("ic-view-module-24px"), // ic-view-module-24px
    ic_view_quilt_24px("ic-view-quilt-24px"), // ic-view-quilt-24px
    ic_view_stream_24px("ic-view-stream-24px"), // ic-view-stream-24px
    ic_view_week_24px("ic-view-week-24px"), // ic-view-week-24px
    ic_visibility_24px("ic-visibility-24px"), // ic-visibility-24px
    ic_visibility_off_24px("ic-visibility-off-24px"), // ic-visibility-off-24px
    ic_watch_later_24px("ic-watch-later-24px"), // ic-watch-later-24px
    ic_work_24px("ic-work-24px"), // ic-work-24px
    ic_youtube_searched_for_24px("ic-youtube-searched-for-24px"), // ic-youtube-searched-for-24px
    ic_zoom_in_24px("ic-zoom-in-24px"), // ic-zoom-in-24px
    ic_zoom_out_24px("ic-zoom-out-24px"), // ic-zoom-out-24px
    ic_add_alert_24px("ic-add-alert-24px"), // ic-add-alert-24px
    ic_error_24px("ic-error-24px"), // ic-error-24px
    ic_error_outline_24px("ic-error-outline-24px"), // ic-error-outline-24px
    ic_warning_24px("ic-warning-24px"), // ic-warning-24px
    ic_add_to_queue_24px("ic-add-to-queue-24px"), // ic-add-to-queue-24px
    ic_airplay_24px("ic-airplay-24px"), // ic-airplay-24px
    ic_album_24px("ic-album-24px"), // ic-album-24px
    ic_art_track_24px("ic-art-track-24px"), // ic-art-track-24px
    ic_av_timer_24px("ic-av-timer-24px"), // ic-av-timer-24px
    ic_branding_watermark_24px("ic-branding-watermark-24px"), // ic-branding-watermark-24px
    ic_call_to_action_24px("ic-call-to-action-24px"), // ic-call-to-action-24px
    ic_closed_caption_24px("ic-closed-caption-24px"), // ic-closed-caption-24px
    ic_equalizer_24px("ic-equalizer-24px"), // ic-equalizer-24px
    ic_explicit_24px("ic-explicit-24px"), // ic-explicit-24px
    ic_fast_forward_24px("ic-fast-forward-24px"), // ic-fast-forward-24px
    ic_fast_rewind_24px("ic-fast-rewind-24px"), // ic-fast-rewind-24px
    ic_featured_play_list_24px("ic-featured-play-list-24px"), // ic-featured-play-list-24px
    ic_featured_video_24px("ic-featured-video-24px"), // ic-featured-video-24px
    ic_fiber_dvr_24px("ic-fiber-dvr-24px"), // ic-fiber-dvr-24px
    ic_fiber_manual_record_24px("ic-fiber-manual-record-24px"), // ic-fiber-manual-record-24px
    ic_fiber_new_24px("ic-fiber-new-24px"), // ic-fiber-new-24px
    ic_fiber_pin_24px("ic-fiber-pin-24px"), // ic-fiber-pin-24px
    ic_fiber_smart_record_24px("ic-fiber-smart-record-24px"), // ic-fiber-smart-record-24px
    ic_forward_10_24px("ic-forward-10-24px"), // ic-forward-10-24px
    ic_forward_30_24px("ic-forward-30-24px"), // ic-forward-30-24px
    ic_forward_5_24px("ic-forward-5-24px"), // ic-forward-5-24px
    ic_games_24px("ic-games-24px"), // ic-games-24px
    ic_hd_24px("ic-hd-24px"), // ic-hd-24px
    ic_hearing_24px("ic-hearing-24px"), // ic-hearing-24px
    ic_high_quality_24px("ic-high-quality-24px"), // ic-high-quality-24px
    ic_library_add_24px("ic-library-add-24px"), // ic-library-add-24px
    ic_library_books_24px("ic-library-books-24px"), // ic-library-books-24px
    ic_library_music_24px("ic-library-music-24px"), // ic-library-music-24px
    ic_loop_24px("ic-loop-24px"), // ic-loop-24px
    ic_mic_24px("ic-mic-24px"), // ic-mic-24px
    ic_mic_none_24px("ic-mic-none-24px"), // ic-mic-none-24px
    ic_mic_off_24px("ic-mic-off-24px"), // ic-mic-off-24px
    ic_movie_24px("ic-movie-24px"), // ic-movie-24px
    ic_music_video_24px("ic-music-video-24px"), // ic-music-video-24px
    ic_new_releases_24px("ic-new-releases-24px"), // ic-new-releases-24px
    ic_not_interested_24px("ic-not-interested-24px"), // ic-not-interested-24px
    ic_note_24px("ic-note-24px"), // ic-note-24px
    ic_pause_24px("ic-pause-24px"), // ic-pause-24px
    ic_pause_circle_filled_24px("ic-pause-circle-filled-24px"), // ic-pause-circle-filled-24px
    ic_pause_circle_outline_24px("ic-pause-circle-outline-24px"), // ic-pause-circle-outline-24px
    ic_play_arrow_24px("ic-play-arrow-24px"), // ic-play-arrow-24px
    ic_play_circle_filled_24px("ic-play-circle-filled-24px"), // ic-play-circle-filled-24px
    ic_play_circle_outline_24px("ic-play-circle-outline-24px"), // ic-play-circle-outline-24px
    ic_playlist_add_24px("ic-playlist-add-24px"), // ic-playlist-add-24px
    ic_playlist_add_check_24px("ic-playlist-add-check-24px"), // ic-playlist-add-check-24px
    ic_playlist_play_24px("ic-playlist-play-24px"), // ic-playlist-play-24px
    ic_queue_24px("ic-queue-24px"), // ic-queue-24px
    ic_queue_music_24px("ic-queue-music-24px"), // ic-queue-music-24px
    ic_queue_play_next_24px("ic-queue-play-next-24px"), // ic-queue-play-next-24px
    ic_radio_24px("ic-radio-24px"), // ic-radio-24px
    ic_recent_actors_24px("ic-recent-actors-24px"), // ic-recent-actors-24px
    ic_remove_from_queue_24px("ic-remove-from-queue-24px"), // ic-remove-from-queue-24px
    ic_repeat_24px("ic-repeat-24px"), // ic-repeat-24px
    ic_repeat_one_24px("ic-repeat-one-24px"), // ic-repeat-one-24px
    ic_replay_10_24px("ic-replay-10-24px"), // ic-replay-10-24px
    ic_replay_24px("ic-replay-24px"), // ic-replay-24px
    ic_replay_30_24px("ic-replay-30-24px"), // ic-replay-30-24px
    ic_replay_5_24px("ic-replay-5-24px"), // ic-replay-5-24px
    ic_shuffle_24px("ic-shuffle-24px"), // ic-shuffle-24px
    ic_skip_next_24px("ic-skip-next-24px"), // ic-skip-next-24px
    ic_skip_previous_24px("ic-skip-previous-24px"), // ic-skip-previous-24px
    ic_slow_motion_video_24px("ic-slow-motion-video-24px"), // ic-slow-motion-video-24px
    ic_snooze_24px("ic-snooze-24px"), // ic-snooze-24px
    ic_sort_by_alpha_24px("ic-sort-by-alpha-24px"), // ic-sort-by-alpha-24px
    ic_stop_24px("ic-stop-24px"), // ic-stop-24px
    ic_subscriptions_24px("ic-subscriptions-24px"), // ic-subscriptions-24px
    ic_subtitles_24px("ic-subtitles-24px"), // ic-subtitles-24px
    ic_surround_sound_24px("ic-surround-sound-24px"), // ic-surround-sound-24px
    ic_video_call_24px("ic-video-call-24px"), // ic-video-call-24px
    ic_video_label_24px("ic-video-label-24px"), // ic-video-label-24px
    ic_video_library_24px("ic-video-library-24px"), // ic-video-library-24px
    ic_videocam_24px("ic-videocam-24px"), // ic-videocam-24px
    ic_videocam_off_24px("ic-videocam-off-24px"), // ic-videocam-off-24px
    ic_volume_down_24px("ic-volume-down-24px"), // ic-volume-down-24px
    ic_volume_mute_24px("ic-volume-mute-24px"), // ic-volume-mute-24px
    ic_volume_off_24px("ic-volume-off-24px"), // ic-volume-off-24px
    ic_volume_up_24px("ic-volume-up-24px"), // ic-volume-up-24px
    ic_web_24px("ic-web-24px"), // ic-web-24px
    ic_web_asset_24px("ic-web-asset-24px"), // ic-web-asset-24px
    ic_business_24px("ic-business-24px"), // ic-business-24px
    ic_call_24px("ic-call-24px"), // ic-call-24px
    ic_call_end_24px("ic-call-end-24px"), // ic-call-end-24px
    ic_call_made_24px("ic-call-made-24px"), // ic-call-made-24px
    ic_call_merge_24px("ic-call-merge-24px"), // ic-call-merge-24px
    ic_call_missed_24px("ic-call-missed-24px"), // ic-call-missed-24px
    ic_call_missed_outgoing_24px("ic-call-missed-outgoing-24px"), // ic-call-missed-outgoing-24px
    ic_call_received_24px("ic-call-received-24px"), // ic-call-received-24px
    ic_call_split_24px("ic-call-split-24px"), // ic-call-split-24px
    ic_chat_24px("ic-chat-24px"), // ic-chat-24px
    ic_chat_bubble_24px("ic-chat-bubble-24px"), // ic-chat-bubble-24px
    ic_chat_bubble_outline_24px("ic-chat-bubble-outline-24px"), // ic-chat-bubble-outline-24px
    ic_clear_all_24px("ic-clear-all-24px"), // ic-clear-all-24px
    ic_comment_24px("ic-comment-24px"), // ic-comment-24px
    ic_contact_mail_24px("ic-contact-mail-24px"), // ic-contact-mail-24px
    ic_contact_phone_24px("ic-contact-phone-24px"), // ic-contact-phone-24px
    ic_contacts_24px("ic-contacts-24px"), // ic-contacts-24px
    ic_dialer_sip_24px("ic-dialer-sip-24px"), // ic-dialer-sip-24px
    ic_dialpad_24px("ic-dialpad-24px"), // ic-dialpad-24px
    ic_email_24px("ic-email-24px"), // ic-email-24px
    ic_forum_24px("ic-forum-24px"), // ic-forum-24px
    ic_import_contacts_24px("ic-import-contacts-24px"), // ic-import-contacts-24px
    ic_import_export_24px("ic-import-export-24px"), // ic-import-export-24px
    ic_invert_colors_off_24px("ic-invert-colors-off-24px"), // ic-invert-colors-off-24px
    ic_live_help_24px("ic-live-help-24px"), // ic-live-help-24px
    ic_location_off_24px("ic-location-off-24px"), // ic-location-off-24px
    ic_location_on_24px("ic-location-on-24px"), // ic-location-on-24px
    ic_mail_outline_24px("ic-mail-outline-24px"), // ic-mail-outline-24px
    ic_message_24px("ic-message-24px"), // ic-message-24px
    ic_no_sim_24px("ic-no-sim-24px"), // ic-no-sim-24px
    ic_phone_24px("ic-phone-24px"), // ic-phone-24px
    ic_phonelink_erase_24px("ic-phonelink-erase-24px"), // ic-phonelink-erase-24px
    ic_phonelink_lock_24px("ic-phonelink-lock-24px"), // ic-phonelink-lock-24px
    ic_phonelink_ring_24px("ic-phonelink-ring-24px"), // ic-phonelink-ring-24px
    ic_phonelink_setup_24px("ic-phonelink-setup-24px"), // ic-phonelink-setup-24px
    ic_portable_wifi_off_24px("ic-portable-wifi-off-24px"), // ic-portable-wifi-off-24px
    ic_present_to_all_24px("ic-present-to-all-24px"), // ic-present-to-all-24px
    ic_ring_volume_24px("ic-ring-volume-24px"), // ic-ring-volume-24px
    ic_rss_feed_24px("ic-rss-feed-24px"), // ic-rss-feed-24px
    ic_screen_share_24px("ic-screen-share-24px"), // ic-screen-share-24px
    ic_speaker_phone_24px("ic-speaker-phone-24px"), // ic-speaker-phone-24px
    ic_stay_current_landscape_24px("ic-stay-current-landscape-24px"), // ic-stay-current-landscape-24px
    ic_stay_current_portrait_24px("ic-stay-current-portrait-24px"), // ic-stay-current-portrait-24px
    ic_stay_primary_landscape_24px("ic-stay-primary-landscape-24px"), // ic-stay-primary-landscape-24px
    ic_stay_primary_portrait_24px("ic-stay-primary-portrait-24px"), // ic-stay-primary-portrait-24px
    ic_stop_screen_share_24px("ic-stop-screen-share-24px"), // ic-stop-screen-share-24px
    ic_swap_calls_24px("ic-swap-calls-24px"), // ic-swap-calls-24px
    ic_textsms_24px("ic-textsms-24px"), // ic-textsms-24px
    ic_voicemail_24px("ic-voicemail-24px"), // ic-voicemail-24px
    ic_vpn_key_24px("ic-vpn-key-24px"), // ic-vpn-key-24px
    ic_add_24px("ic-add-24px"), // ic-add-24px
    ic_add_box_24px("ic-add-box-24px"), // ic-add-box-24px
    ic_add_circle_24px("ic-add-circle-24px"), // ic-add-circle-24px
    ic_add_circle_outline_24px("ic-add-circle-outline-24px"), // ic-add-circle-outline-24px
    ic_archive_24px("ic-archive-24px"), // ic-archive-24px
    ic_backspace_24px("ic-backspace-24px"), // ic-backspace-24px
    ic_block_24px("ic-block-24px"), // ic-block-24px
    ic_clear_24px("ic-clear-24px"), // ic-clear-24px
    ic_content_copy_24px("ic-content-copy-24px"), // ic-content-copy-24px
    ic_content_cut_24px("ic-content-cut-24px"), // ic-content-cut-24px
    ic_content_paste_24px("ic-content-paste-24px"), // ic-content-paste-24px
    ic_create_24px("ic-create-24px"), // ic-create-24px
    ic_delete_sweep_24px("ic-delete-sweep-24px"), // ic-delete-sweep-24px
    ic_drafts_24px("ic-drafts-24px"), // ic-drafts-24px
    ic_filter_list_24px("ic-filter-list-24px"), // ic-filter-list-24px
    ic_flag_24px("ic-flag-24px"), // ic-flag-24px
    ic_font_download_24px("ic-font-download-24px"), // ic-font-download-24px
    ic_forward_24px("ic-forward-24px"), // ic-forward-24px
    ic_gesture_24px("ic-gesture-24px"), // ic-gesture-24px
    ic_inbox_24px("ic-inbox-24px"), // ic-inbox-24px
    ic_link_24px("ic-link-24px"), // ic-link-24px
    ic_low_priority_24px("ic-low-priority-24px"), // ic-low-priority-24px
    ic_mail_24px("ic-mail-24px"), // ic-mail-24px
    ic_markunread_24px("ic-markunread-24px"), // ic-markunread-24px
    ic_move_to_inbox_24px("ic-move-to-inbox-24px"), // ic-move-to-inbox-24px
    ic_next_week_24px("ic-next-week-24px"), // ic-next-week-24px
    ic_redo_24px("ic-redo-24px"), // ic-redo-24px
    ic_remove_24px("ic-remove-24px"), // ic-remove-24px
    ic_remove_circle_24px("ic-remove-circle-24px"), // ic-remove-circle-24px
    ic_remove_circle_outline_24px("ic-remove-circle-outline-24px"), // ic-remove-circle-outline-24px
    ic_reply_24px("ic-reply-24px"), // ic-reply-24px
    ic_reply_all_24px("ic-reply-all-24px"), // ic-reply-all-24px
    ic_report_24px("ic-report-24px"), // ic-report-24px
    ic_save_24px("ic-save-24px"), // ic-save-24px
    ic_select_all_24px("ic-select-all-24px"), // ic-select-all-24px
    ic_send_24px("ic-send-24px"), // ic-send-24px
    ic_sort_24px("ic-sort-24px"), // ic-sort-24px
    ic_text_format_24px("ic-text-format-24px"), // ic-text-format-24px
    ic_unarchive_24px("ic-unarchive-24px"), // ic-unarchive-24px
    ic_undo_24px("ic-undo-24px"), // ic-undo-24px
    ic_weekend_24px("ic-weekend-24px"), // ic-weekend-24px
    ic_access_alarm_24px("ic-access-alarm-24px"), // ic-access-alarm-24px
    ic_access_alarms_24px("ic-access-alarms-24px"), // ic-access-alarms-24px
    ic_access_time_24px("ic-access-time-24px"), // ic-access-time-24px
    ic_add_alarm_24px("ic-add-alarm-24px"), // ic-add-alarm-24px
    ic_airplanemode_active_24px("ic-airplanemode-active-24px"), // ic-airplanemode-active-24px
    ic_airplanemode_inactive_24px("ic-airplanemode-inactive-24px"), // ic-airplanemode-inactive-24px
    ic_battery_20_24px("ic-battery-20-24px"), // ic-battery-20-24px
    ic_battery_30_24px("ic-battery-30-24px"), // ic-battery-30-24px
    ic_battery_50_24px("ic-battery-50-24px"), // ic-battery-50-24px
    ic_battery_60_24px("ic-battery-60-24px"), // ic-battery-60-24px
    ic_battery_80_24px("ic-battery-80-24px"), // ic-battery-80-24px
    ic_battery_90_24px("ic-battery-90-24px"), // ic-battery-90-24px
    ic_battery_alert_24px("ic-battery-alert-24px"), // ic-battery-alert-24px
    ic_battery_charging_20_24px("ic-battery-charging-20-24px"), // ic-battery-charging-20-24px
    ic_battery_charging_30_24px("ic-battery-charging-30-24px"), // ic-battery-charging-30-24px
    ic_battery_charging_50_24px("ic-battery-charging-50-24px"), // ic-battery-charging-50-24px
    ic_battery_charging_60_24px("ic-battery-charging-60-24px"), // ic-battery-charging-60-24px
    ic_battery_charging_80_24px("ic-battery-charging-80-24px"), // ic-battery-charging-80-24px
    ic_battery_charging_90_24px("ic-battery-charging-90-24px"), // ic-battery-charging-90-24px
    ic_battery_charging_full_24px("ic-battery-charging-full-24px"), // ic-battery-charging-full-24px
    ic_battery_full_24px("ic-battery-full-24px"), // ic-battery-full-24px
    ic_battery_std_24px("ic-battery-std-24px"), // ic-battery-std-24px
    ic_battery_unknown_24px("ic-battery-unknown-24px"), // ic-battery-unknown-24px
    ic_bluetooth_24px("ic-bluetooth-24px"), // ic-bluetooth-24px
    ic_bluetooth_connected_24px("ic-bluetooth-connected-24px"), // ic-bluetooth-connected-24px
    ic_bluetooth_disabled_24px("ic-bluetooth-disabled-24px"), // ic-bluetooth-disabled-24px
    ic_bluetooth_searching_24px("ic-bluetooth-searching-24px"), // ic-bluetooth-searching-24px
    ic_brightness_auto_24px("ic-brightness-auto-24px"), // ic-brightness-auto-24px
    ic_brightness_high_24px("ic-brightness-high-24px"), // ic-brightness-high-24px
    ic_brightness_low_24px("ic-brightness-low-24px"), // ic-brightness-low-24px
    ic_brightness_medium_24px("ic-brightness-medium-24px"), // ic-brightness-medium-24px
    ic_data_usage_24px("ic-data-usage-24px"), // ic-data-usage-24px
    ic_developer_mode_24px("ic-developer-mode-24px"), // ic-developer-mode-24px
    ic_devices_24px("ic-devices-24px"), // ic-devices-24px
    ic_dvr_24px("ic-dvr-24px"), // ic-dvr-24px
    ic_gps_fixed_24px("ic-gps-fixed-24px"), // ic-gps-fixed-24px
    ic_gps_not_fixed_24px("ic-gps-not-fixed-24px"), // ic-gps-not-fixed-24px
    ic_gps_off_24px("ic-gps-off-24px"), // ic-gps-off-24px
    ic_graphic_eq_24px("ic-graphic-eq-24px"), // ic-graphic-eq-24px
    ic_location_disabled_24px("ic-location-disabled-24px"), // ic-location-disabled-24px
    ic_location_searching_24px("ic-location-searching-24px"), // ic-location-searching-24px
    ic_network_cell_24px("ic-network-cell-24px"), // ic-network-cell-24px
    ic_network_wifi_24px("ic-network-wifi-24px"), // ic-network-wifi-24px
    ic_nfc_24px("ic-nfc-24px"), // ic-nfc-24px
    ic_screen_lock_landscape_24px("ic-screen-lock-landscape-24px"), // ic-screen-lock-landscape-24px
    ic_screen_lock_portrait_24px("ic-screen-lock-portrait-24px"), // ic-screen-lock-portrait-24px
    ic_screen_lock_rotation_24px("ic-screen-lock-rotation-24px"), // ic-screen-lock-rotation-24px
    ic_screen_rotation_24px("ic-screen-rotation-24px"), // ic-screen-rotation-24px
    ic_sd_storage_24px("ic-sd-storage-24px"), // ic-sd-storage-24px
    ic_settings_system_daydream_24px("ic-settings-system-daydream-24px"), // ic-settings-system-daydream-24px
    ic_signal_cellular_0_bar_24px("ic-signal-cellular-0-bar-24px"), // ic-signal-cellular-0-bar-24px
    ic_signal_cellular_1_bar_24px("ic-signal-cellular-1-bar-24px"), // ic-signal-cellular-1-bar-24px
    ic_signal_cellular_2_bar_24px("ic-signal-cellular-2-bar-24px"), // ic-signal-cellular-2-bar-24px
    ic_signal_cellular_3_bar_24px("ic-signal-cellular-3-bar-24px"), // ic-signal-cellular-3-bar-24px
    ic_signal_cellular_4_bar_24px("ic-signal-cellular-4-bar-24px"), // ic-signal-cellular-4-bar-24px
    ic_signal_cellular_connected_no_internet_0_bar_24px("ic-signal-cellular-connected-no-internet-0-bar-24px"), // ic-signal-cellular-connected-no-internet-0-bar-24px
    ic_signal_cellular_connected_no_internet_1_bar_24px("ic-signal-cellular-connected-no-internet-1-bar-24px"), // ic-signal-cellular-connected-no-internet-1-bar-24px
    ic_signal_cellular_connected_no_internet_2_bar_24px("ic-signal-cellular-connected-no-internet-2-bar-24px"), // ic-signal-cellular-connected-no-internet-2-bar-24px
    ic_signal_cellular_connected_no_internet_3_bar_24px("ic-signal-cellular-connected-no-internet-3-bar-24px"), // ic-signal-cellular-connected-no-internet-3-bar-24px
    ic_signal_cellular_connected_no_internet_4_bar_24px("ic-signal-cellular-connected-no-internet-4-bar-24px"), // ic-signal-cellular-connected-no-internet-4-bar-24px
    ic_signal_cellular_no_sim_24px("ic-signal-cellular-no-sim-24px"), // ic-signal-cellular-no-sim-24px
    ic_signal_cellular_null_24px("ic-signal-cellular-null-24px"), // ic-signal-cellular-null-24px
    ic_signal_cellular_off_24px("ic-signal-cellular-off-24px"), // ic-signal-cellular-off-24px
    ic_signal_wifi_0_bar_24px("ic-signal-wifi-0-bar-24px"), // ic-signal-wifi-0-bar-24px
    ic_signal_wifi_1_bar_24px("ic-signal-wifi-1-bar-24px"), // ic-signal-wifi-1-bar-24px
    ic_signal_wifi_1_bar_lock_24px("ic-signal-wifi-1-bar-lock-24px"), // ic-signal-wifi-1-bar-lock-24px
    ic_signal_wifi_2_bar_24px("ic-signal-wifi-2-bar-24px"), // ic-signal-wifi-2-bar-24px
    ic_signal_wifi_2_bar_lock_24px("ic-signal-wifi-2-bar-lock-24px"), // ic-signal-wifi-2-bar-lock-24px
    ic_signal_wifi_3_bar_24px("ic-signal-wifi-3-bar-24px"), // ic-signal-wifi-3-bar-24px
    ic_signal_wifi_3_bar_lock_24px("ic-signal-wifi-3-bar-lock-24px"), // ic-signal-wifi-3-bar-lock-24px
    ic_signal_wifi_4_bar_24px("ic-signal-wifi-4-bar-24px"), // ic-signal-wifi-4-bar-24px
    ic_signal_wifi_4_bar_lock_24px("ic-signal-wifi-4-bar-lock-24px"), // ic-signal-wifi-4-bar-lock-24px
    ic_signal_wifi_off_24px("ic-signal-wifi-off-24px"), // ic-signal-wifi-off-24px
    ic_signal_wifi_statusbar_1_bar_26x24px("ic-signal-wifi-statusbar-1-bar-26x24px"), // ic-signal-wifi-statusbar-1-bar-26x24px
    ic_signal_wifi_statusbar_2_bar_26x24px("ic-signal-wifi-statusbar-2-bar-26x24px"), // ic-signal-wifi-statusbar-2-bar-26x24px
    ic_signal_wifi_statusbar_3_bar_26x24px("ic-signal-wifi-statusbar-3-bar-26x24px"), // ic-signal-wifi-statusbar-3-bar-26x24px
    ic_signal_wifi_statusbar_4_bar_26x24px("ic-signal-wifi-statusbar-4-bar-26x24px"), // ic-signal-wifi-statusbar-4-bar-26x24px
    ic_signal_wifi_statusbar_connected_no_internet_1_26x24px("ic-signal-wifi-statusbar-connected-no-internet-1-26x24px"), // ic-signal-wifi-statusbar-connected-no-internet-1-26x24px
    ic_signal_wifi_statusbar_connected_no_internet_26x24px("ic-signal-wifi-statusbar-connected-no-internet-26x24px"), // ic-signal-wifi-statusbar-connected-no-internet-26x24px
    ic_signal_wifi_statusbar_connected_no_internet_2_26x24px("ic-signal-wifi-statusbar-connected-no-internet-2-26x24px"), // ic-signal-wifi-statusbar-connected-no-internet-2-26x24px
    ic_signal_wifi_statusbar_connected_no_internet_3_26x24px("ic-signal-wifi-statusbar-connected-no-internet-3-26x24px"), // ic-signal-wifi-statusbar-connected-no-internet-3-26x24px
    ic_signal_wifi_statusbar_connected_no_internet_4_26x24px("ic-signal-wifi-statusbar-connected-no-internet-4-26x24px"), // ic-signal-wifi-statusbar-connected-no-internet-4-26x24px
    ic_signal_wifi_statusbar_not_connected_26x24px("ic-signal-wifi-statusbar-not-connected-26x24px"), // ic-signal-wifi-statusbar-not-connected-26x24px
    ic_signal_wifi_statusbar_null_26x24px("ic-signal-wifi-statusbar-null-26x24px"), // ic-signal-wifi-statusbar-null-26x24px
    ic_storage_24px("ic-storage-24px"), // ic-storage-24px
    ic_usb_24px("ic-usb-24px"), // ic-usb-24px
    ic_wallpaper_24px("ic-wallpaper-24px"), // ic-wallpaper-24px
    ic_widgets_24px("ic-widgets-24px"), // ic-widgets-24px
    ic_wifi_lock_24px("ic-wifi-lock-24px"), // ic-wifi-lock-24px
    ic_wifi_tethering_24px("ic-wifi-tethering-24px"), // ic-wifi-tethering-24px
    ic_attach_file_24px("ic-attach-file-24px"), // ic-attach-file-24px
    ic_attach_money_24px("ic-attach-money-24px"), // ic-attach-money-24px
    ic_border_all_24px("ic-border-all-24px"), // ic-border-all-24px
    ic_border_bottom_24px("ic-border-bottom-24px"), // ic-border-bottom-24px
    ic_border_clear_24px("ic-border-clear-24px"), // ic-border-clear-24px
    ic_border_color_24px("ic-border-color-24px"), // ic-border-color-24px
    ic_border_horizontal_24px("ic-border-horizontal-24px"), // ic-border-horizontal-24px
    ic_border_inner_24px("ic-border-inner-24px"), // ic-border-inner-24px
    ic_border_left_24px("ic-border-left-24px"), // ic-border-left-24px
    ic_border_outer_24px("ic-border-outer-24px"), // ic-border-outer-24px
    ic_border_right_24px("ic-border-right-24px"), // ic-border-right-24px
    ic_border_style_24px("ic-border-style-24px"), // ic-border-style-24px
    ic_border_top_24px("ic-border-top-24px"), // ic-border-top-24px
    ic_border_vertical_24px("ic-border-vertical-24px"), // ic-border-vertical-24px
    ic_bubble_chart_24px("ic-bubble-chart-24px"), // ic-bubble-chart-24px
    ic_drag_handle_24px("ic-drag-handle-24px"), // ic-drag-handle-24px
    ic_format_align_center_24px("ic-format-align-center-24px"), // ic-format-align-center-24px
    ic_format_align_justify_24px("ic-format-align-justify-24px"), // ic-format-align-justify-24px
    ic_format_align_left_24px("ic-format-align-left-24px"), // ic-format-align-left-24px
    ic_format_align_right_24px("ic-format-align-right-24px"), // ic-format-align-right-24px
    ic_format_bold_24px("ic-format-bold-24px"), // ic-format-bold-24px
    ic_format_clear_24px("ic-format-clear-24px"), // ic-format-clear-24px
    ic_format_color_fill_24px("ic-format-color-fill-24px"), // ic-format-color-fill-24px
    ic_format_color_reset_24px("ic-format-color-reset-24px"), // ic-format-color-reset-24px
    ic_format_color_text_24px("ic-format-color-text-24px"), // ic-format-color-text-24px
    ic_format_indent_decrease_24px("ic-format-indent-decrease-24px"), // ic-format-indent-decrease-24px
    ic_format_indent_increase_24px("ic-format-indent-increase-24px"), // ic-format-indent-increase-24px
    ic_format_italic_24px("ic-format-italic-24px"), // ic-format-italic-24px
    ic_format_line_spacing_24px("ic-format-line-spacing-24px"), // ic-format-line-spacing-24px
    ic_format_list_bulleted_24px("ic-format-list-bulleted-24px"), // ic-format-list-bulleted-24px
    ic_format_list_numbered_24px("ic-format-list-numbered-24px"), // ic-format-list-numbered-24px
    ic_format_paint_24px("ic-format-paint-24px"), // ic-format-paint-24px
    ic_format_quote_24px("ic-format-quote-24px"), // ic-format-quote-24px
    ic_format_shapes_24px("ic-format-shapes-24px"), // ic-format-shapes-24px
    ic_format_size_24px("ic-format-size-24px"), // ic-format-size-24px
    ic_format_strikethrough_24px("ic-format-strikethrough-24px"), // ic-format-strikethrough-24px
    ic_format_textdirection_l_to_r_24px("ic-format-textdirection-l-to-r-24px"), // ic-format-textdirection-l-to-r-24px
    ic_format_textdirection_r_to_l_24px("ic-format-textdirection-r-to-l-24px"), // ic-format-textdirection-r-to-l-24px
    ic_format_underlined_24px("ic-format-underlined-24px"), // ic-format-underlined-24px
    ic_functions_24px("ic-functions-24px"), // ic-functions-24px
    ic_highlight_24px("ic-highlight-24px"), // ic-highlight-24px
    ic_insert_chart_24px("ic-insert-chart-24px"), // ic-insert-chart-24px
    ic_insert_comment_24px("ic-insert-comment-24px"), // ic-insert-comment-24px
    ic_insert_drive_file_24px("ic-insert-drive-file-24px"), // ic-insert-drive-file-24px
    ic_insert_emoticon_24px("ic-insert-emoticon-24px"), // ic-insert-emoticon-24px
    ic_insert_invitation_24px("ic-insert-invitation-24px"), // ic-insert-invitation-24px
    ic_insert_link_24px("ic-insert-link-24px"), // ic-insert-link-24px
    ic_insert_photo_24px("ic-insert-photo-24px"), // ic-insert-photo-24px
    ic_linear_scale_24px("ic-linear-scale-24px"), // ic-linear-scale-24px
    ic_merge_type_24px("ic-merge-type-24px"), // ic-merge-type-24px
    ic_mode_comment_24px("ic-mode-comment-24px"), // ic-mode-comment-24px
    ic_mode_edit_24px("ic-mode-edit-24px"), // ic-mode-edit-24px
    ic_monetization_on_24px("ic-monetization-on-24px"), // ic-monetization-on-24px
    ic_money_off_24px("ic-money-off-24px"), // ic-money-off-24px
    ic_multiline_chart_24px("ic-multiline-chart-24px"), // ic-multiline-chart-24px
    ic_pie_chart_24px("ic-pie-chart-24px"), // ic-pie-chart-24px
    ic_pie_chart_outlined_24px("ic-pie-chart-outlined-24px"), // ic-pie-chart-outlined-24px
    ic_publish_24px("ic-publish-24px"), // ic-publish-24px
    ic_short_text_24px("ic-short-text-24px"), // ic-short-text-24px
    ic_show_chart_24px("ic-show-chart-24px"), // ic-show-chart-24px
    ic_space_bar_24px("ic-space-bar-24px"), // ic-space-bar-24px
    ic_strikethrough_s_24px("ic-strikethrough-s-24px"), // ic-strikethrough-s-24px
    ic_text_fields_24px("ic-text-fields-24px"), // ic-text-fields-24px
    ic_title_24px("ic-title-24px"), // ic-title-24px
    ic_vertical_align_bottom_24px("ic-vertical-align-bottom-24px"), // ic-vertical-align-bottom-24px
    ic_vertical_align_center_24px("ic-vertical-align-center-24px"), // ic-vertical-align-center-24px
    ic_vertical_align_top_24px("ic-vertical-align-top-24px"), // ic-vertical-align-top-24px
    ic_wrap_text_24px("ic-wrap-text-24px"), // ic-wrap-text-24px
    ic_attachment_24px("ic-attachment-24px"), // ic-attachment-24px
    ic_cloud_24px("ic-cloud-24px"), // ic-cloud-24px
    ic_cloud_circle_24px("ic-cloud-circle-24px"), // ic-cloud-circle-24px
    ic_cloud_done_24px("ic-cloud-done-24px"), // ic-cloud-done-24px
    ic_cloud_download_24px("ic-cloud-download-24px"), // ic-cloud-download-24px
    ic_cloud_off_24px("ic-cloud-off-24px"), // ic-cloud-off-24px
    ic_cloud_queue_24px("ic-cloud-queue-24px"), // ic-cloud-queue-24px
    ic_cloud_upload_24px("ic-cloud-upload-24px"), // ic-cloud-upload-24px
    ic_create_new_folder_24px("ic-create-new-folder-24px"), // ic-create-new-folder-24px
    ic_file_download_24px("ic-file-download-24px"), // ic-file-download-24px
    ic_file_upload_24px("ic-file-upload-24px"), // ic-file-upload-24px
    ic_folder_24px("ic-folder-24px"), // ic-folder-24px
    ic_folder_open_24px("ic-folder-open-24px"), // ic-folder-open-24px
    ic_folder_shared_24px("ic-folder-shared-24px"), // ic-folder-shared-24px
    ic_cast_24px("ic-cast-24px"), // ic-cast-24px
    ic_cast_connected_24px("ic-cast-connected-24px"), // ic-cast-connected-24px
    ic_computer_24px("ic-computer-24px"), // ic-computer-24px
    ic_desktop_mac_24px("ic-desktop-mac-24px"), // ic-desktop-mac-24px
    ic_desktop_windows_24px("ic-desktop-windows-24px"), // ic-desktop-windows-24px
    ic_developer_board_24px("ic-developer-board-24px"), // ic-developer-board-24px
    ic_device_hub_24px("ic-device-hub-24px"), // ic-device-hub-24px
    ic_devices_other_24px("ic-devices-other-24px"), // ic-devices-other-24px
    ic_dock_24px("ic-dock-24px"), // ic-dock-24px
    ic_gamepad_24px("ic-gamepad-24px"), // ic-gamepad-24px
    ic_headset_24px("ic-headset-24px"), // ic-headset-24px
    ic_headset_mic_24px("ic-headset-mic-24px"), // ic-headset-mic-24px
    ic_keyboard_24px("ic-keyboard-24px"), // ic-keyboard-24px
    ic_keyboard_arrow_down_24px("ic-keyboard-arrow-down-24px"), // ic-keyboard-arrow-down-24px
    ic_keyboard_arrow_left_24px("ic-keyboard-arrow-left-24px"), // ic-keyboard-arrow-left-24px
    ic_keyboard_arrow_right_24px("ic-keyboard-arrow-right-24px"), // ic-keyboard-arrow-right-24px
    ic_keyboard_arrow_up_24px("ic-keyboard-arrow-up-24px"), // ic-keyboard-arrow-up-24px
    ic_keyboard_backspace_24px("ic-keyboard-backspace-24px"), // ic-keyboard-backspace-24px
    ic_keyboard_capslock_24px("ic-keyboard-capslock-24px"), // ic-keyboard-capslock-24px
    ic_keyboard_hide_24px("ic-keyboard-hide-24px"), // ic-keyboard-hide-24px
    ic_keyboard_return_24px("ic-keyboard-return-24px"), // ic-keyboard-return-24px
    ic_keyboard_tab_24px("ic-keyboard-tab-24px"), // ic-keyboard-tab-24px
    ic_keyboard_voice_24px("ic-keyboard-voice-24px"), // ic-keyboard-voice-24px
    ic_laptop_24px("ic-laptop-24px"), // ic-laptop-24px
    ic_laptop_chromebook_24px("ic-laptop-chromebook-24px"), // ic-laptop-chromebook-24px
    ic_laptop_mac_24px("ic-laptop-mac-24px"), // ic-laptop-mac-24px
    ic_laptop_windows_24px("ic-laptop-windows-24px"), // ic-laptop-windows-24px
    ic_memory_24px("ic-memory-24px"), // ic-memory-24px
    ic_mouse_24px("ic-mouse-24px"), // ic-mouse-24px
    ic_phone_android_24px("ic-phone-android-24px"), // ic-phone-android-24px
    ic_phone_iphone_24px("ic-phone-iphone-24px"), // ic-phone-iphone-24px
    ic_phonelink_24px("ic-phonelink-24px"), // ic-phonelink-24px
    ic_phonelink_off_24px("ic-phonelink-off-24px"), // ic-phonelink-off-24px
    ic_power_input_24px("ic-power-input-24px"), // ic-power-input-24px
    ic_router_24px("ic-router-24px"), // ic-router-24px
    ic_scanner_24px("ic-scanner-24px"), // ic-scanner-24px
    ic_security_24px("ic-security-24px"), // ic-security-24px
    ic_sim_card_24px("ic-sim-card-24px"), // ic-sim-card-24px
    ic_smartphone_24px("ic-smartphone-24px"), // ic-smartphone-24px
    ic_speaker_24px("ic-speaker-24px"), // ic-speaker-24px
    ic_speaker_group_24px("ic-speaker-group-24px"), // ic-speaker-group-24px
    ic_tablet_24px("ic-tablet-24px"), // ic-tablet-24px
    ic_tablet_android_24px("ic-tablet-android-24px"), // ic-tablet-android-24px
    ic_tablet_mac_24px("ic-tablet-mac-24px"), // ic-tablet-mac-24px
    ic_toys_24px("ic-toys-24px"), // ic-toys-24px
    ic_tv_24px("ic-tv-24px"), // ic-tv-24px
    ic_videogame_asset_24px("ic-videogame-asset-24px"), // ic-videogame-asset-24px
    ic_watch_24px("ic-watch-24px"), // ic-watch-24px
    MaterialIcons_Regular("MaterialIcons-Regular"), // MaterialIcons-Regular
    ic_add_a_photo_24px("ic-add-a-photo-24px"), // ic-add-a-photo-24px
    ic_add_to_photos_24px("ic-add-to-photos-24px"), // ic-add-to-photos-24px
    ic_adjust_24px("ic-adjust-24px"), // ic-adjust-24px
    ic_assistant_24px("ic-assistant-24px"), // ic-assistant-24px
    ic_assistant_photo_24px("ic-assistant-photo-24px"), // ic-assistant-photo-24px
    ic_audiotrack_24px("ic-audiotrack-24px"), // ic-audiotrack-24px
    ic_blur_circular_24px("ic-blur-circular-24px"), // ic-blur-circular-24px
    ic_blur_linear_24px("ic-blur-linear-24px"), // ic-blur-linear-24px
    ic_blur_off_24px("ic-blur-off-24px"), // ic-blur-off-24px
    ic_blur_on_24px("ic-blur-on-24px"), // ic-blur-on-24px
    ic_brightness_1_24px("ic-brightness-1-24px"), // ic-brightness-1-24px
    ic_brightness_2_24px("ic-brightness-2-24px"), // ic-brightness-2-24px
    ic_brightness_3_24px("ic-brightness-3-24px"), // ic-brightness-3-24px
    ic_brightness_4_24px("ic-brightness-4-24px"), // ic-brightness-4-24px
    ic_brightness_5_24px("ic-brightness-5-24px"), // ic-brightness-5-24px
    ic_brightness_6_24px("ic-brightness-6-24px"), // ic-brightness-6-24px
    ic_brightness_7_24px("ic-brightness-7-24px"), // ic-brightness-7-24px
    ic_broken_image_24px("ic-broken-image-24px"), // ic-broken-image-24px
    ic_brush_24px("ic-brush-24px"), // ic-brush-24px
    ic_burst_mode_24px("ic-burst-mode-24px"), // ic-burst-mode-24px
    ic_camera_24px("ic-camera-24px"), // ic-camera-24px
    ic_camera_alt_24px("ic-camera-alt-24px"), // ic-camera-alt-24px
    ic_camera_front_24px("ic-camera-front-24px"), // ic-camera-front-24px
    ic_camera_rear_24px("ic-camera-rear-24px"), // ic-camera-rear-24px
    ic_camera_roll_24px("ic-camera-roll-24px"), // ic-camera-roll-24px
    ic_center_focus_strong_24px("ic-center-focus-strong-24px"), // ic-center-focus-strong-24px
    ic_center_focus_weak_24px("ic-center-focus-weak-24px"), // ic-center-focus-weak-24px
    ic_collections_24px("ic-collections-24px"), // ic-collections-24px
    ic_collections_bookmark_24px("ic-collections-bookmark-24px"), // ic-collections-bookmark-24px
    ic_color_lens_24px("ic-color-lens-24px"), // ic-color-lens-24px
    ic_colorize_24px("ic-colorize-24px"), // ic-colorize-24px
    ic_compare_24px("ic-compare-24px"), // ic-compare-24px
    ic_control_point_24px("ic-control-point-24px"), // ic-control-point-24px
    ic_control_point_duplicate_24px("ic-control-point-duplicate-24px"), // ic-control-point-duplicate-24px
    ic_crop_16_9_24px("ic-crop-16-9-24px"), // ic-crop-16-9-24px
    ic_crop_24px("ic-crop-24px"), // ic-crop-24px
    ic_crop_3_2_24px("ic-crop-3-2-24px"), // ic-crop-3-2-24px
    ic_crop_5_4_24px("ic-crop-5-4-24px"), // ic-crop-5-4-24px
    ic_crop_7_5_24px("ic-crop-7-5-24px"), // ic-crop-7-5-24px
    ic_crop_din_24px("ic-crop-din-24px"), // ic-crop-din-24px
    ic_crop_free_24px("ic-crop-free-24px"), // ic-crop-free-24px
    ic_crop_landscape_24px("ic-crop-landscape-24px"), // ic-crop-landscape-24px
    ic_crop_original_24px("ic-crop-original-24px"), // ic-crop-original-24px
    ic_crop_portrait_24px("ic-crop-portrait-24px"), // ic-crop-portrait-24px
    ic_crop_rotate_24px("ic-crop-rotate-24px"), // ic-crop-rotate-24px
    ic_crop_square_24px("ic-crop-square-24px"), // ic-crop-square-24px
    ic_dehaze_24px("ic-dehaze-24px"), // ic-dehaze-24px
    ic_details_24px("ic-details-24px"), // ic-details-24px
    ic_edit_24px("ic-edit-24px"), // ic-edit-24px
    ic_exposure_24px("ic-exposure-24px"), // ic-exposure-24px
    ic_exposure_neg_1_24px("ic-exposure-neg-1-24px"), // ic-exposure-neg-1-24px
    ic_exposure_neg_2_24px("ic-exposure-neg-2-24px"), // ic-exposure-neg-2-24px
    ic_exposure_plus_1_24px("ic-exposure-plus-1-24px"), // ic-exposure-plus-1-24px
    ic_exposure_plus_2_24px("ic-exposure-plus-2-24px"), // ic-exposure-plus-2-24px
    ic_exposure_zero_24px("ic-exposure-zero-24px"), // ic-exposure-zero-24px
    ic_filter_1_24px("ic-filter-1-24px"), // ic-filter-1-24px
    ic_filter_24px("ic-filter-24px"), // ic-filter-24px
    ic_filter_2_24px("ic-filter-2-24px"), // ic-filter-2-24px
    ic_filter_3_24px("ic-filter-3-24px"), // ic-filter-3-24px
    ic_filter_4_24px("ic-filter-4-24px"), // ic-filter-4-24px
    ic_filter_5_24px("ic-filter-5-24px"), // ic-filter-5-24px
    ic_filter_6_24px("ic-filter-6-24px"), // ic-filter-6-24px
    ic_filter_7_24px("ic-filter-7-24px"), // ic-filter-7-24px
    ic_filter_8_24px("ic-filter-8-24px"), // ic-filter-8-24px
    ic_filter_9_24px("ic-filter-9-24px"), // ic-filter-9-24px
    ic_filter_9_plus_24px("ic-filter-9-plus-24px"), // ic-filter-9-plus-24px
    ic_filter_b_and_w_24px("ic-filter-b-and-w-24px"), // ic-filter-b-and-w-24px
    ic_filter_center_focus_24px("ic-filter-center-focus-24px"), // ic-filter-center-focus-24px
    ic_filter_drama_24px("ic-filter-drama-24px"), // ic-filter-drama-24px
    ic_filter_frames_24px("ic-filter-frames-24px"), // ic-filter-frames-24px
    ic_filter_hdr_24px("ic-filter-hdr-24px"), // ic-filter-hdr-24px
    ic_filter_none_24px("ic-filter-none-24px"), // ic-filter-none-24px
    ic_filter_tilt_shift_24px("ic-filter-tilt-shift-24px"), // ic-filter-tilt-shift-24px
    ic_filter_vintage_24px("ic-filter-vintage-24px"), // ic-filter-vintage-24px
    ic_flare_24px("ic-flare-24px"), // ic-flare-24px
    ic_flash_auto_24px("ic-flash-auto-24px"), // ic-flash-auto-24px
    ic_flash_off_24px("ic-flash-off-24px"), // ic-flash-off-24px
    ic_flash_on_24px("ic-flash-on-24px"), // ic-flash-on-24px
    ic_flip_24px("ic-flip-24px"), // ic-flip-24px
    ic_gradient_24px("ic-gradient-24px"), // ic-gradient-24px
    ic_grain_24px("ic-grain-24px"), // ic-grain-24px
    ic_grid_off_24px("ic-grid-off-24px"), // ic-grid-off-24px
    ic_grid_on_24px("ic-grid-on-24px"), // ic-grid-on-24px
    ic_hdr_off_24px("ic-hdr-off-24px"), // ic-hdr-off-24px
    ic_hdr_on_24px("ic-hdr-on-24px"), // ic-hdr-on-24px
    ic_hdr_strong_24px("ic-hdr-strong-24px"), // ic-hdr-strong-24px
    ic_hdr_weak_24px("ic-hdr-weak-24px"), // ic-hdr-weak-24px
    ic_healing_24px("ic-healing-24px"), // ic-healing-24px
    ic_image_24px("ic-image-24px"), // ic-image-24px
    ic_image_aspect_ratio_24px("ic-image-aspect-ratio-24px"), // ic-image-aspect-ratio-24px
    ic_iso_24px("ic-iso-24px"), // ic-iso-24px
    ic_landscape_24px("ic-landscape-24px"), // ic-landscape-24px
    ic_leak_add_24px("ic-leak-add-24px"), // ic-leak-add-24px
    ic_leak_remove_24px("ic-leak-remove-24px"), // ic-leak-remove-24px
    ic_lens_24px("ic-lens-24px"), // ic-lens-24px
    ic_linked_camera_24px("ic-linked-camera-24px"), // ic-linked-camera-24px
    ic_looks_24px("ic-looks-24px"), // ic-looks-24px
    ic_looks_3_24px("ic-looks-3-24px"), // ic-looks-3-24px
    ic_looks_4_24px("ic-looks-4-24px"), // ic-looks-4-24px
    ic_looks_5_24px("ic-looks-5-24px"), // ic-looks-5-24px
    ic_looks_6_24px("ic-looks-6-24px"), // ic-looks-6-24px
    ic_looks_one_24px("ic-looks-one-24px"), // ic-looks-one-24px
    ic_looks_two_24px("ic-looks-two-24px"), // ic-looks-two-24px
    ic_loupe_24px("ic-loupe-24px"), // ic-loupe-24px
    ic_monochrome_photos_24px("ic-monochrome-photos-24px"), // ic-monochrome-photos-24px
    ic_movie_creation_24px("ic-movie-creation-24px"), // ic-movie-creation-24px
    ic_movie_filter_24px("ic-movie-filter-24px"), // ic-movie-filter-24px
    ic_music_note_24px("ic-music-note-24px"), // ic-music-note-24px
    ic_nature_24px("ic-nature-24px"), // ic-nature-24px
    ic_nature_people_24px("ic-nature-people-24px"), // ic-nature-people-24px
    ic_navigate_before_24px("ic-navigate-before-24px"), // ic-navigate-before-24px
    ic_navigate_next_24px("ic-navigate-next-24px"), // ic-navigate-next-24px
    ic_palette_24px("ic-palette-24px"), // ic-palette-24px
    ic_panorama_24px("ic-panorama-24px"), // ic-panorama-24px
    ic_panorama_fish_eye_24px("ic-panorama-fish-eye-24px"), // ic-panorama-fish-eye-24px
    ic_panorama_horizontal_24px("ic-panorama-horizontal-24px"), // ic-panorama-horizontal-24px
    ic_panorama_vertical_24px("ic-panorama-vertical-24px"), // ic-panorama-vertical-24px
    ic_panorama_wide_angle_24px("ic-panorama-wide-angle-24px"), // ic-panorama-wide-angle-24px
    ic_photo_24px("ic-photo-24px"), // ic-photo-24px
    ic_photo_album_24px("ic-photo-album-24px"), // ic-photo-album-24px
    ic_photo_camera_24px("ic-photo-camera-24px"), // ic-photo-camera-24px
    ic_photo_filter_24px("ic-photo-filter-24px"), // ic-photo-filter-24px
    ic_photo_library_24px("ic-photo-library-24px"), // ic-photo-library-24px
    ic_photo_size_select_actual_24px("ic-photo-size-select-actual-24px"), // ic-photo-size-select-actual-24px
    ic_photo_size_select_large_24px("ic-photo-size-select-large-24px"), // ic-photo-size-select-large-24px
    ic_photo_size_select_small_24px("ic-photo-size-select-small-24px"), // ic-photo-size-select-small-24px
    ic_picture_as_pdf_24px("ic-picture-as-pdf-24px"), // ic-picture-as-pdf-24px
    ic_portrait_24px("ic-portrait-24px"), // ic-portrait-24px
    ic_remove_red_eye_24px("ic-remove-red-eye-24px"), // ic-remove-red-eye-24px
    ic_rotate_90_degrees_ccw_24px("ic-rotate-90-degrees-ccw-24px"), // ic-rotate-90-degrees-ccw-24px
    ic_rotate_left_24px("ic-rotate-left-24px"), // ic-rotate-left-24px
    ic_rotate_right_24px("ic-rotate-right-24px"), // ic-rotate-right-24px
    ic_slideshow_24px("ic-slideshow-24px"), // ic-slideshow-24px
    ic_straighten_24px("ic-straighten-24px"), // ic-straighten-24px
    ic_style_24px("ic-style-24px"), // ic-style-24px
    ic_switch_camera_24px("ic-switch-camera-24px"), // ic-switch-camera-24px
    ic_switch_video_24px("ic-switch-video-24px"), // ic-switch-video-24px
    ic_tag_faces_24px("ic-tag-faces-24px"), // ic-tag-faces-24px
    ic_texture_24px("ic-texture-24px"), // ic-texture-24px
    ic_timelapse_24px("ic-timelapse-24px"), // ic-timelapse-24px
    ic_timer_10_24px("ic-timer-10-24px"), // ic-timer-10-24px
    ic_timer_24px("ic-timer-24px"), // ic-timer-24px
    ic_timer_3_24px("ic-timer-3-24px"), // ic-timer-3-24px
    ic_timer_off_24px("ic-timer-off-24px"), // ic-timer-off-24px
    ic_tonality_24px("ic-tonality-24px"), // ic-tonality-24px
    ic_transform_24px("ic-transform-24px"), // ic-transform-24px
    ic_tune_24px("ic-tune-24px"), // ic-tune-24px
    ic_view_comfy_24px("ic-view-comfy-24px"), // ic-view-comfy-24px
    ic_view_compact_24px("ic-view-compact-24px"), // ic-view-compact-24px
    ic_vignette_24px("ic-vignette-24px"), // ic-vignette-24px
    ic_wb_auto_24px("ic-wb-auto-24px"), // ic-wb-auto-24px
    ic_wb_cloudy_24px("ic-wb-cloudy-24px"), // ic-wb-cloudy-24px
    ic_wb_incandescent_24px("ic-wb-incandescent-24px"), // ic-wb-incandescent-24px
    ic_wb_iridescent_24px("ic-wb-iridescent-24px"), // ic-wb-iridescent-24px
    ic_wb_sunny_24px("ic-wb-sunny-24px"), // ic-wb-sunny-24px
    ic_add_location_24px("ic-add-location-24px"), // ic-add-location-24px
    ic_beenhere_24px("ic-beenhere-24px"), // ic-beenhere-24px
    ic_directions_24px("ic-directions-24px"), // ic-directions-24px
    ic_directions_bike_24px("ic-directions-bike-24px"), // ic-directions-bike-24px
    ic_directions_boat_24px("ic-directions-boat-24px"), // ic-directions-boat-24px
    ic_directions_bus_24px("ic-directions-bus-24px"), // ic-directions-bus-24px
    ic_directions_car_24px("ic-directions-car-24px"), // ic-directions-car-24px
    ic_directions_railway_24px("ic-directions-railway-24px"), // ic-directions-railway-24px
    ic_directions_run_24px("ic-directions-run-24px"), // ic-directions-run-24px
    ic_directions_subway_24px("ic-directions-subway-24px"), // ic-directions-subway-24px
    ic_directions_transit_24px("ic-directions-transit-24px"), // ic-directions-transit-24px
    ic_directions_walk_24px("ic-directions-walk-24px"), // ic-directions-walk-24px
    ic_edit_location_24px("ic-edit-location-24px"), // ic-edit-location-24px
    ic_ev_station_24px("ic-ev-station-24px"), // ic-ev-station-24px
    ic_flight_24px("ic-flight-24px"), // ic-flight-24px
    ic_hotel_24px("ic-hotel-24px"), // ic-hotel-24px
    ic_layers_24px("ic-layers-24px"), // ic-layers-24px
    ic_layers_clear_24px("ic-layers-clear-24px"), // ic-layers-clear-24px
    ic_local_activity_24px("ic-local-activity-24px"), // ic-local-activity-24px
    ic_local_airport_24px("ic-local-airport-24px"), // ic-local-airport-24px
    ic_local_atm_24px("ic-local-atm-24px"), // ic-local-atm-24px
    ic_local_bar_24px("ic-local-bar-24px"), // ic-local-bar-24px
    ic_local_cafe_24px("ic-local-cafe-24px"), // ic-local-cafe-24px
    ic_local_car_wash_24px("ic-local-car-wash-24px"), // ic-local-car-wash-24px
    ic_local_convenience_store_24px("ic-local-convenience-store-24px"), // ic-local-convenience-store-24px
    ic_local_dining_24px("ic-local-dining-24px"), // ic-local-dining-24px
    ic_local_drink_24px("ic-local-drink-24px"), // ic-local-drink-24px
    ic_local_florist_24px("ic-local-florist-24px"), // ic-local-florist-24px
    ic_local_gas_station_24px("ic-local-gas-station-24px"), // ic-local-gas-station-24px
    ic_local_grocery_store_24px("ic-local-grocery-store-24px"), // ic-local-grocery-store-24px
    ic_local_hospital_24px("ic-local-hospital-24px"), // ic-local-hospital-24px
    ic_local_hotel_24px("ic-local-hotel-24px"), // ic-local-hotel-24px
    ic_local_laundry_service_24px("ic-local-laundry-service-24px"), // ic-local-laundry-service-24px
    ic_local_library_24px("ic-local-library-24px"), // ic-local-library-24px
    ic_local_mall_24px("ic-local-mall-24px"), // ic-local-mall-24px
    ic_local_movies_24px("ic-local-movies-24px"), // ic-local-movies-24px
    ic_local_offer_24px("ic-local-offer-24px"), // ic-local-offer-24px
    ic_local_parking_24px("ic-local-parking-24px"), // ic-local-parking-24px
    ic_local_pharmacy_24px("ic-local-pharmacy-24px"), // ic-local-pharmacy-24px
    ic_local_phone_24px("ic-local-phone-24px"), // ic-local-phone-24px
    ic_local_pizza_24px("ic-local-pizza-24px"), // ic-local-pizza-24px
    ic_local_play_24px("ic-local-play-24px"), // ic-local-play-24px
    ic_local_post_office_24px("ic-local-post-office-24px"), // ic-local-post-office-24px
    ic_local_printshop_24px("ic-local-printshop-24px"), // ic-local-printshop-24px
    ic_local_see_24px("ic-local-see-24px"), // ic-local-see-24px
    ic_local_shipping_24px("ic-local-shipping-24px"), // ic-local-shipping-24px
    ic_local_taxi_24px("ic-local-taxi-24px"), // ic-local-taxi-24px
    ic_map_24px("ic-map-24px"), // ic-map-24px
    ic_my_location_24px("ic-my-location-24px"), // ic-my-location-24px
    ic_navigation_24px("ic-navigation-24px"), // ic-navigation-24px
    ic_near_me_24px("ic-near-me-24px"), // ic-near-me-24px
    ic_person_pin_24px("ic-person-pin-24px"), // ic-person-pin-24px
    ic_person_pin_circle_24px("ic-person-pin-circle-24px"), // ic-person-pin-circle-24px
    ic_pin_drop_24px("ic-pin-drop-24px"), // ic-pin-drop-24px
    ic_place_24px("ic-place-24px"), // ic-place-24px
    ic_rate_review_24px("ic-rate-review-24px"), // ic-rate-review-24px
    ic_restaurant_24px("ic-restaurant-24px"), // ic-restaurant-24px
    ic_restaurant_menu_24px("ic-restaurant-menu-24px"), // ic-restaurant-menu-24px
    ic_satellite_24px("ic-satellite-24px"), // ic-satellite-24px
    ic_store_mall_directory_24px("ic-store-mall-directory-24px"), // ic-store-mall-directory-24px
    ic_streetview_24px("ic-streetview-24px"), // ic-streetview-24px
    ic_subway_24px("ic-subway-24px"), // ic-subway-24px
    ic_terrain_24px("ic-terrain-24px"), // ic-terrain-24px
    ic_traffic_24px("ic-traffic-24px"), // ic-traffic-24px
    ic_train_24px("ic-train-24px"), // ic-train-24px
    ic_tram_24px("ic-tram-24px"), // ic-tram-24px
    ic_transfer_within_a_station_24px("ic-transfer-within-a-station-24px"), // ic-transfer-within-a-station-24px
    ic_zoom_out_map_24px("ic-zoom-out-map-24px"), // ic-zoom-out-map-24px
    ic_apps_24px("ic-apps-24px"), // ic-apps-24px
    ic_arrow_back_24px("ic-arrow-back-24px"), // ic-arrow-back-24px
    ic_arrow_downward_24px("ic-arrow-downward-24px"), // ic-arrow-downward-24px
    ic_arrow_drop_down_24px("ic-arrow-drop-down-24px"), // ic-arrow-drop-down-24px
    ic_arrow_drop_down_circle_24px("ic-arrow-drop-down-circle-24px"), // ic-arrow-drop-down-circle-24px
    ic_arrow_drop_up_24px("ic-arrow-drop-up-24px"), // ic-arrow-drop-up-24px
    ic_arrow_forward_24px("ic-arrow-forward-24px"), // ic-arrow-forward-24px
    ic_arrow_upward_24px("ic-arrow-upward-24px"), // ic-arrow-upward-24px
    ic_cancel_24px("ic-cancel-24px"), // ic-cancel-24px
    ic_check_24px("ic-check-24px"), // ic-check-24px
    ic_chevron_left_24px("ic-chevron-left-24px"), // ic-chevron-left-24px
    ic_chevron_right_24px("ic-chevron-right-24px"), // ic-chevron-right-24px
    ic_close_24px("ic-close-24px"), // ic-close-24px
    ic_expand_less_24px("ic-expand-less-24px"), // ic-expand-less-24px
    ic_expand_more_24px("ic-expand-more-24px"), // ic-expand-more-24px
    ic_first_page_24px("ic-first-page-24px"), // ic-first-page-24px
    ic_fullscreen_24px("ic-fullscreen-24px"), // ic-fullscreen-24px
    ic_fullscreen_exit_24px("ic-fullscreen-exit-24px"), // ic-fullscreen-exit-24px
    ic_last_page_24px("ic-last-page-24px"), // ic-last-page-24px
    ic_menu_24px("ic-menu-24px"), // ic-menu-24px
    ic_more_horiz_24px("ic-more-horiz-24px"), // ic-more-horiz-24px
    ic_more_vert_24px("ic-more-vert-24px"), // ic-more-vert-24px
    ic_refresh_24px("ic-refresh-24px"), // ic-refresh-24px
    ic_subdirectory_arrow_left_24px("ic-subdirectory-arrow-left-24px"), // ic-subdirectory-arrow-left-24px
    ic_subdirectory_arrow_right_24px("ic-subdirectory-arrow-right-24px"), // ic-subdirectory-arrow-right-24px
    ic_unfold_less_24px("ic-unfold-less-24px"), // ic-unfold-less-24px
    ic_unfold_more_24px("ic-unfold-more-24px"), // ic-unfold-more-24px
    ic_adb_24px("ic-adb-24px"), // ic-adb-24px
    ic_airline_seat_flat_24px("ic-airline-seat-flat-24px"), // ic-airline-seat-flat-24px
    ic_airline_seat_flat_angled_24px("ic-airline-seat-flat-angled-24px"), // ic-airline-seat-flat-angled-24px
    ic_airline_seat_individual_suite_24px("ic-airline-seat-individual-suite-24px"), // ic-airline-seat-individual-suite-24px
    ic_airline_seat_legroom_extra_24px("ic-airline-seat-legroom-extra-24px"), // ic-airline-seat-legroom-extra-24px
    ic_airline_seat_legroom_normal_24px("ic-airline-seat-legroom-normal-24px"), // ic-airline-seat-legroom-normal-24px
    ic_airline_seat_legroom_reduced_24px("ic-airline-seat-legroom-reduced-24px"), // ic-airline-seat-legroom-reduced-24px
    ic_airline_seat_recline_extra_24px("ic-airline-seat-recline-extra-24px"), // ic-airline-seat-recline-extra-24px
    ic_airline_seat_recline_normal_24px("ic-airline-seat-recline-normal-24px"), // ic-airline-seat-recline-normal-24px
    ic_bluetooth_audio_24px("ic-bluetooth-audio-24px"), // ic-bluetooth-audio-24px
    ic_confirmation_number_24px("ic-confirmation-number-24px"), // ic-confirmation-number-24px
    ic_disc_full_24px("ic-disc-full-24px"), // ic-disc-full-24px
    ic_do_not_disturb_24px("ic-do-not-disturb-24px"), // ic-do-not-disturb-24px
    ic_do_not_disturb_alt_24px("ic-do-not-disturb-alt-24px"), // ic-do-not-disturb-alt-24px
    ic_do_not_disturb_off_24px("ic-do-not-disturb-off-24px"), // ic-do-not-disturb-off-24px
    ic_do_not_disturb_on_24px("ic-do-not-disturb-on-24px"), // ic-do-not-disturb-on-24px
    ic_drive_eta_24px("ic-drive-eta-24px"), // ic-drive-eta-24px
    ic_enhanced_encryption_24px("ic-enhanced-encryption-24px"), // ic-enhanced-encryption-24px
    ic_event_available_24px("ic-event-available-24px"), // ic-event-available-24px
    ic_event_busy_24px("ic-event-busy-24px"), // ic-event-busy-24px
    ic_event_note_24px("ic-event-note-24px"), // ic-event-note-24px
    ic_folder_special_24px("ic-folder-special-24px"), // ic-folder-special-24px
    ic_live_tv_24px("ic-live-tv-24px"), // ic-live-tv-24px
    ic_mms_24px("ic-mms-24px"), // ic-mms-24px
    ic_more_24px("ic-more-24px"), // ic-more-24px
    ic_network_check_24px("ic-network-check-24px"), // ic-network-check-24px
    ic_network_locked_24px("ic-network-locked-24px"), // ic-network-locked-24px
    ic_no_encryption_24px("ic-no-encryption-24px"), // ic-no-encryption-24px
    ic_ondemand_video_24px("ic-ondemand-video-24px"), // ic-ondemand-video-24px
    ic_personal_video_24px("ic-personal-video-24px"), // ic-personal-video-24px
    ic_phone_bluetooth_speaker_24px("ic-phone-bluetooth-speaker-24px"), // ic-phone-bluetooth-speaker-24px
    ic_phone_forwarded_24px("ic-phone-forwarded-24px"), // ic-phone-forwarded-24px
    ic_phone_in_talk_24px("ic-phone-in-talk-24px"), // ic-phone-in-talk-24px
    ic_phone_locked_24px("ic-phone-locked-24px"), // ic-phone-locked-24px
    ic_phone_missed_24px("ic-phone-missed-24px"), // ic-phone-missed-24px
    ic_phone_paused_24px("ic-phone-paused-24px"), // ic-phone-paused-24px
    ic_power_24px("ic-power-24px"), // ic-power-24px
    ic_priority_high_12px("ic-priority-high-12px"), // ic-priority-high-12px
    ic_priority_high_24px("ic-priority-high-24px"), // ic-priority-high-24px
    ic_rv_hookup_24px("ic-rv-hookup-24px"), // ic-rv-hookup-24px
    ic_sd_card_24px("ic-sd-card-24px"), // ic-sd-card-24px
    ic_sim_card_alert_24px("ic-sim-card-alert-24px"), // ic-sim-card-alert-24px
    ic_sms_24px("ic-sms-24px"), // ic-sms-24px
    ic_sms_failed_24px("ic-sms-failed-24px"), // ic-sms-failed-24px
    ic_sync_24px("ic-sync-24px"), // ic-sync-24px
    ic_sync_disabled_24px("ic-sync-disabled-24px"), // ic-sync-disabled-24px
    ic_sync_problem_24px("ic-sync-problem-24px"), // ic-sync-problem-24px
    ic_system_update_24px("ic-system-update-24px"), // ic-system-update-24px
    ic_tap_and_play_24px("ic-tap-and-play-24px"), // ic-tap-and-play-24px
    ic_time_to_leave_24px("ic-time-to-leave-24px"), // ic-time-to-leave-24px
    ic_vibration_24px("ic-vibration-24px"), // ic-vibration-24px
    ic_voice_chat_24px("ic-voice-chat-24px"), // ic-voice-chat-24px
    ic_vpn_lock_24px("ic-vpn-lock-24px"), // ic-vpn-lock-24px
    ic_wc_24px("ic-wc-24px"), // ic-wc-24px
    ic_wifi_24px("ic-wifi-24px"), // ic-wifi-24px
    ic_ac_unit_24px("ic-ac-unit-24px"), // ic-ac-unit-24px
    ic_airport_shuttle_24px("ic-airport-shuttle-24px"), // ic-airport-shuttle-24px
    ic_all_inclusive_24px("ic-all-inclusive-24px"), // ic-all-inclusive-24px
    ic_beach_access_24px("ic-beach-access-24px"), // ic-beach-access-24px
    ic_business_center_24px("ic-business-center-24px"), // ic-business-center-24px
    ic_casino_24px("ic-casino-24px"), // ic-casino-24px
    ic_child_care_24px("ic-child-care-24px"), // ic-child-care-24px
    ic_child_friendly_24px("ic-child-friendly-24px"), // ic-child-friendly-24px
    ic_fitness_center_24px("ic-fitness-center-24px"), // ic-fitness-center-24px
    ic_free_breakfast_24px("ic-free-breakfast-24px"), // ic-free-breakfast-24px
    ic_golf_course_24px("ic-golf-course-24px"), // ic-golf-course-24px
    ic_hot_tub_24px("ic-hot-tub-24px"), // ic-hot-tub-24px
    ic_kitchen_24px("ic-kitchen-24px"), // ic-kitchen-24px
    ic_pool_24px("ic-pool-24px"), // ic-pool-24px
    ic_room_service_24px("ic-room-service-24px"), // ic-room-service-24px
    ic_smoke_free_24px("ic-smoke-free-24px"), // ic-smoke-free-24px
    ic_smoking_rooms_24px("ic-smoking-rooms-24px"), // ic-smoking-rooms-24px
    ic_spa_24px("ic-spa-24px"), // ic-spa-24px
    ic_cake_24px("ic-cake-24px"), // ic-cake-24px
    ic_domain_24px("ic-domain-24px"), // ic-domain-24px
    ic_group_24px("ic-group-24px"), // ic-group-24px
    ic_group_add_24px("ic-group-add-24px"), // ic-group-add-24px
    ic_location_city_24px("ic-location-city-24px"), // ic-location-city-24px
    ic_mood_24px("ic-mood-24px"), // ic-mood-24px
    ic_mood_bad_24px("ic-mood-bad-24px"), // ic-mood-bad-24px
    ic_notifications_24px("ic-notifications-24px"), // ic-notifications-24px
    ic_notifications_active_24px("ic-notifications-active-24px"), // ic-notifications-active-24px
    ic_notifications_none_24px("ic-notifications-none-24px"), // ic-notifications-none-24px
    ic_notifications_off_24px("ic-notifications-off-24px"), // ic-notifications-off-24px
    ic_notifications_paused_24px("ic-notifications-paused-24px"), // ic-notifications-paused-24px
    ic_pages_24px("ic-pages-24px"), // ic-pages-24px
    ic_party_mode_24px("ic-party-mode-24px"), // ic-party-mode-24px
    ic_people_24px("ic-people-24px"), // ic-people-24px
    ic_people_outline_24px("ic-people-outline-24px"), // ic-people-outline-24px
    ic_person_24px("ic-person-24px"), // ic-person-24px
    ic_person_add_24px("ic-person-add-24px"), // ic-person-add-24px
    ic_person_outline_24px("ic-person-outline-24px"), // ic-person-outline-24px
    ic_plus_one_24px("ic-plus-one-24px"), // ic-plus-one-24px
    ic_poll_24px("ic-poll-24px"), // ic-poll-24px
    ic_public_24px("ic-public-24px"), // ic-public-24px
    ic_school_24px("ic-school-24px"), // ic-school-24px
    ic_sentiment_dissatisfied_24px("ic-sentiment-dissatisfied-24px"), // ic-sentiment-dissatisfied-24px
    ic_sentiment_neutral_24px("ic-sentiment-neutral-24px"), // ic-sentiment-neutral-24px
    ic_sentiment_satisfied_24px("ic-sentiment-satisfied-24px"), // ic-sentiment-satisfied-24px
    ic_sentiment_very_dissatisfied_24px("ic-sentiment-very-dissatisfied-24px"), // ic-sentiment-very-dissatisfied-24px
    ic_sentiment_very_satisfied_24px("ic-sentiment-very-satisfied-24px"), // ic-sentiment-very-satisfied-24px
    ic_share_24px("ic-share-24px"), // ic-share-24px
    ic_whatshot_24px("ic-whatshot-24px"), // ic-whatshot-24px
    ic_check_box_24px("ic-check-box-24px"), // ic-check-box-24px
    ic_check_box_outline_blank_24px("ic-check-box-outline-blank-24px"), // ic-check-box-outline-blank-24px
    ic_indeterminate_check_box_24px("ic-indeterminate-check-box-24px"), // ic-indeterminate-check-box-24px
    ic_radio_button_checked_24px("ic-radio-button-checked-24px"), // ic-radio-button-checked-24px
    ic_radio_button_unchecked_24px("ic-radio-button-unchecked-24px"), // ic-radio-button-unchecked-24px
    ic_star_24px("ic-star-24px"), // ic-star-24px
    ic_star_border_24px("ic-star-border-24px"), // ic-star-border-24px
    ic_star_half_24px("ic-star-half-24px"); // ic-star-half-24px

    private String id;

    private MaterialDesignSymbol(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }

    public static int length() {
        return values().length;
    }

    public static MaterialDesignSymbol random() {
        MaterialDesignSymbol[] values = values();
        return values[new Random().nextInt(values.length)];
    }
}
